language: node_js
node_js:
  - '8'
cache:
  directories:
    - /home/travis/.rvm/
    - node_modules # NPM packages

env:
  - PULL_REQUEST_ID: ${TRAVIS_PULL_REQUEST}

addons:
  artifacts:
    # ...
    working_dir: coverage

stages:
  - name: test
    if: type IN (push)
    
  - name: release
    if: tag =~ /v.*/

jobs:
  include:
    - stage: test
      - script: scripts/stages/pre-test
      - script: scripts/stages/test
    
    - stage: release
      - script: scripts/stages/release
      - script: scripts/stages/pre-release