language: ruby
rvm:
  - 2.5.0
env:
  - TRAVIS_NODE_VERSION="8"

before_install:
  - 'sudo apt-get install unzip'
  - scripts/install/sonar-scanner
  - scripts/install/ruby
  - scripts/install/changelog-generator
  - scripts/install/chandler

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

after_success: 
  - 'npm run coveralls'
  - 'npm run sonar'
  - 'npm run changelog'
  - 'npm run github-release'