language: node_js
node_js:
  - '8'
cache:
  directories:
    - /home/travis/.rvm/
    - node_modules # NPM packages

before_install:
  - 'sudo apt-get install unzip'
  - scripts/install/sonar-scanner
  - rvm install 2.5.0
  - scripts/install/changelog-generator
  - scripts/install/chandler

stages:
  - name: test
  - name: release
    if: branch = master AND NOT type = pull_request

jobs:
  include:
    - stage: test
      script: npm test
    - stage: test
      script: npm run coveralls
    - stage: test
      script: 'scripts/sonar-pullrequest'

    - stage: release
      script: npm run changelog
      script: npm run github-release